###
GET http://localhost:8080/tournaments

###
POST http://localhost:8082/tournaments
Content-Type: application/json

  {
    "name": "test5",
    "date": "2024-09-09",
    "rankRange": [
      1000,
      3000
    ],
    "status": "open",
    "region": "asia",
    "playerList": null
  }

###
DELETE http://localhost:8080/tournaments/2

###
GET http://localhost:8080/tournaments/1

###
POST http://localhost:8082/tournaments/1/playerlist/1