trigger:
  branches:
    include:
      - cloudCI  # Replace with the branch you want to trigger the pipeline

pool:
  name: 'Default'  # Replace with the exact name of your self-hosted agent pool

steps:
  # Step 1: Check out the repository using the service connection
  - checkout: self
    name: 'Check out code'
    persistCredentials: true  # Ensures that the credentials are persisted for any future Git operations
    # Add the service connection explicitly if it's not the default connection
    serviceConnection: github.com_Shirosensei  # Replace with the exact name of your GitHub service connection if necessary

  # Step 2: Build with Maven (JDK 21 is already installed on the machine)
  - script: |
      mvn clean package -DskipTests
    displayName: 'Build with Maven'

  # Step 3: Deploy to Azure Spring Apps
  - powershell: |
      az spring app deploy `
        --name tournament-service `
        --service tournament-matchmaking `  # Note: Corrected the typo "tournamnet" to "tournament" here.
        --resource-group cs203 `
        --artifact-path target/project-0.0.1-SNAPSHOT.jar
    displayName: 'Deploy to Azure Spring Apps'
