spring.application.name=project
spring.datasource.url=jdbc:postgresql://localhost:5432/cs203
spring.datasource.username=postgres
spring.datasource.password=1212
# ${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true