###
GET http://localhost:8080/tournaments

###
POST http://localhost:8080/tournaments
Content-Type: application/json

  {
    "name": "3",
    "date": "2024-12-12",
    "rankRange": [
      3,
      5
    ],
    "status": "closed",
    "region": "east"
  }

###
DELETE http://localhost:8080/tournaments/2

###
GET http://localhost:8080/tournaments/55